mysite/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views

#app_name='blog'

urlpatterns =[
     url(r'^admin/', admin.site.urls),
     url(r'^$', views.post_list, name='post_list'),

    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),

    #url(r'^post/poem/$', views.post_poem, name='post_poem'),

    url(r'^post/new/$', views.post_new, name='post_new'),

    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),


    #url(r'^post/(?P<pk>\d+)/delete/$', views.delete_post, name='delete_post'),
    url(r'^register/$', views.register , name='register'),
    url(r'^newpass/$', views.new_pass , name='new_pass'),
    url(r'^logout_view/$', views.logout_view, name='logout_view'),

    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^drafts/$',views.post_draft_list,name='post_draft_list'),
    url(r'^category/list/$', views.category_list, name='category_list'),
    url(r'^(?P<name>(\w+\s*)*)/(?P<num>\d+)$', views.filtered_post_list, name='filtered_post_list'),
    url(r'^category/(?P<name>\w+\s*\w+)/(?P<pk>\d+)/remove/$', views.category_remove, name='category_remove'),




    url(r'^poems/$', views.poem_pg, name='poem_pg'),
    url(r'^articles/$', views.article_pg, name='article_pg'),
    url(r'^reviews/$', views.review_pg, name='review_pg'),

    #here pk is used so that every page opened can have its own primary key
    #the pk is allotted by default




  #  url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),




#url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
]













"""



urlpatterns = [
    url(r'^$', views.Indexview.as_view(), name='post_list'),

    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='post_detail'),

   url(r'^post/new/$', views.PostCreate.as_view(),name='post_new'),

    url(r'^post/(?P<pk>\d+)/edit/$',views.PostUpdate.as_view(),name='post_edit'),


    #url(r'^post/(?<pk>\d+)/delete/$',views.PostDelete.as_view(),name='post_delete'),

url(r'^register/$', views.UserFormView.as_view(), name='register'),
]

#meaning of self, empty r'^$'??

#form-template in registr.html, post_form, post_edit

"""

blog/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.conf import settings


def upload_location(instance,filename):
    return "%s/%s"%(instance.id,filename)

class Post(models.Model):
   # author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1) # to associate a post with a user which may or may not be admin
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True, default=None)
    category = models.ForeignKey('blog.Category', related_name='posts')
    drafts = models.BooleanField(default=False)
    publish=models.DateField(auto_now=False,auto_now_add=False)  #this is the to publish date
    image=models.ImageField(upload_to=upload_location,null=True,blank=True,width_field="width_field",height_field="height_field")
    width_field=models.IntegerField(default=0)
    height_field=models.IntegerField(default=0)
    #image=models.FileField(null=True, blank=True)


    def get_absolute_url(self):
        return reverse('view:post_detail',kwargs={'pk':self.pk})


"""
    def publish(self):
        self.published_date = timezone.now()
        self.cleaned_data['award_grant_date'] = None
        self.save()

    def __str__(self):
        return self.title
"""


class Category(models.Model):
    category_type = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return self.category_type

blog/forms.py
from django import forms

from .models import Post , Category
from django.contrib.auth.models import User

class PostForm(forms.ModelForm):

    class Meta:
        model = Post #will follow the Post Model
        fields = ( 'title' ,'text', 'category','image','drafts','publish')

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','email','password']

blog/views.py
#from .forms import CategoryForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.utils import timezone
from .models import Post ,Category
from django.shortcuts import render, get_object_or_404
from .forms import PostForm
from django.shortcuts import redirect               #redirect users to whatever page they want
from django.views.generic import View
from .forms import UserForm, PostForm
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render
from django.db.models import Q
from django.contrib.auth.forms import UserCreationForm
#from django.core.context_processors import csrf
from django.core.urlresolvers import reverse
from django import http
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.db.models import Q
from django.contrib.auth.models import User



def poem_pg(request):
    posts = Post.objects.all()
    categories = Category.objects.all

    # test code of paginator

    context = {
        'posts': posts,
        'categories': categories,
    }

    return render(request, 'blog/poem_pg.html', context)


def article_pg(request):
    posts = Post.objects.all()
    categories = Category.objects.all

    # test code of paginator

    context = {
        'posts': posts,
        'categories': categories,
    }

    return render(request, 'blog/article_pg.html', context)



def review_pg(request):
    posts = Post.objects.all()
    categories = Category.objects.all

    # test code of paginator

    context = {
        'posts': posts,
        'categories': categories,
    }

    return render(request, 'blog/review_pg.html', context)




@login_required
def category_remove(request, name, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    return HttpResponse("<html><h1>Category successfully deleted</h1></html>")
    #return redirect('blog.views.category_list')


def post_remove(request, pk):
    #post = get_object_or_404(Post, pk=pk)
    u = Post.objects.get(pk=pk).delete()
    return HttpResponse("<html><h1>Post successfully deleted</h1></html>")
    
    """posts=Post.objects.all()
    categories = Category.objects.all
    context = {
    'categories': categories,
    'posts':posts,
    }"""
    


def filtered_post_list(request, name, num):
    # filter post list by category number and if its is published
    posts = Post.objects.filter(category__pk=num, published_date__isnull=False).order_by('-published_date') #decending order
    categories = Category.objects.all

    # test code of paginator

    context = {
        'posts': posts,
        'categories': categories,
    }

    return render(request, 'blog/post_list.html', context)


#CATEGORY_list called by categories at the last of the page, BLOG_SIDEBAR NOT USED
def category_list(request):
    categories = Category.objects.all
    context = {
        'categories': categories
    }

    return render(request, 'blog/category_list.html', context)




def logout_view(request):
    logout(request)
    posts = Post.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts})





def login_user(request):
    if request.method == "POST":
        mail = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=mail, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                posts = Post.objects.all()
                return render(request, 'blog/post_list.html', {'posts': posts})
            else:
                return render(request, 'blog/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'blog/login.html', {'error_message': 'Invalid login'})
    return render(request, 'blog/login.html')



def post_list(request):
    posts = Post.objects.filter(drafts=False).filter(published_date__lte=timezone.now()).order_by('published_date')
    categories = Category.objects.all
    query=request.GET.get("q")
    if query:
        #queryset_list=queryset_list.filter, cant use queryset as queryset is empty
        posts = posts.filter(
            Q(title__icontains=query)|
            Q(text__icontains=query)|
            Q(author__first_name__icontains=query)
            ).distinct()

    return render(request,'blog/post_list.html', {'posts': posts},{'categories':categories})




#filter means show this item only which is in query


def post_detail(request, pk):  #matches url of type post/2005
    """if request.user.is_authenticated():
        #username = request.user.username
        post = get_object_or_404(Post, pk=pk)
        try:
            user_id = int(request.POST['pk'])
            user = User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return render(request, 'blog/post_detail.html', {'post': post})
        categories = Category.objects.all()
        return render(request, 'blog/post_detail.html', {'post': post})
    else:"""
    post = get_object_or_404(Post, pk=pk)
    #post=Post.objects.filter(author=request.user).order_by('-created_date')
    categories = Category.objects.all()
    return render(request, 'blog/post_detail.html', {'post': post})


#means only staff or admin users can chnge the stuff

""" if request.user.is_staff or request.user.is_superuser:
        raise Http404

    if not request.user.is_authenticated():
        raise Http404"""

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)    #method name -GET or Post is specified in the dictionary value
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            #post.user = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

"""
def delete_post(request,pk):
   #+some code to check if New belongs to logged in user
   u = Post.objects.get(pk=pk)
   u.delete()
   posts=Post.objects.all()
   return render(request,'blog/post_list.html', {'posts': posts})
"""

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    categories = Category.objects.all
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=pk)
    else:
        form = PostForm(instance=post)

    context = {
        'form': form,
        'categories': categories
    }
    return render(request, 'blog/post_edit.html', context)

def new_pass(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        #u = User.objects.get(username='username')
        u = form.cleaned_data['username']
        password = form.cleaned_data['password']
        u.set_password(password)
        u.save()
        #return render(request, 'blog/login.html')
        return HttpResponse("password changed")

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password, email=email)
        subject = "Thank you for registering"
        message = "Thank you for registering at CreativityUnplugged. Welcome to the LitLand."
        from_email = settings.EMAIL_HOST_USER
        to_list = [user.email, settings.EMAIL_HOST_USER]
        send_mail(subject,message,from_email,to_list,fail_silently=True)
        messages.success(request,'Thank you for registering!')
        
        if user is not None:
            if user.is_active:
            	q=1
            	return render(request,'blog/login.html', {'q': q})
        return render(request,'blog/login.html', {'q': q})
        """
                login(request, user)
                posts = Post.objects.all()
                return render(request, 'blog/post_list.html', {'posts': posts}) 
        #return render(request.self.template_name,{'form':form})
        """
        
        #return render(request, 'blog/login.html')

    context ={
        "form": form,
    }
    return render(request, 'blog/registration_form.html', context)

#a decorator to ensure that for this function to execute login is required






def post_draft_list(request):
    posts=Post.objects.filter(drafts=True).order_by('created_date')
    return render(request,'blog/post_draft_list.html',{'posts':posts})

#posts=Post.objects.filter(drafts=True).filter(published_date__isnull=True).order_by('created_date')

blog/templates/blog/article_pg.html
{%extends 'blog/base.html' %}

{%block article%}

{%for post in posts%}
{%if post.category.category_type == "Articles"%}

<div class="postA">
<h4><a href="{% url 'post_detail' pk=post.pk %}" >{{ post.title }}</a></h4>

{%endif%}
{%endfor%}
{%endblock%}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
<meta charset="utf-8" >
<!--utf a unicode system only eg unicode- giving 4bytes to int in java -->

<title>{%block title%}SavouringCreativity{%endblock%}</title>
<!--below 2 are the bootstrap references -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<!--imports lobster font from google fonts-->
<link  rel="stylesheet" type="text/css"  href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">  
<link  rel="stylesheet" type="text/css"  href="//fonts.googleapis.com/css?family=Satisfy">  

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<!--CSS link has to come at the end-->
<link rel="stylesheet" href="{% static 'css/blog.css' %}">  


<!alert box>
<script type="text/javascript">  //anonymous func
function msg()
{ document.getElementById('show').onclick=alert('please check the details carefully.');}

</script>

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {box-sizing:border-box}
body {font-family: Verdana,sans-serif;}
.mySlides {display:none}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Caption text */
.text {
  color: black;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  height: 13px;
  width: 13px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active {
  background-color: #717171;
}

/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
}

@-webkit-keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

@keyframes fade {
  from {opacity: .4} 
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .text {font-size: 11px}
}
</style>



</head> 
<!__Nav bar__>


{%comment%}
<body data-spy="scroll" data-target="#myScrollspy" data-offset="20" >
<ul class= "nav navbar-nav"  class="nav nav-pills nav-stacked">   so that tabs come in pill forms
{%endcomment%}



<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.7";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

{%comment%}

https://developers.facebook.com/docs/plugins/comments
for a particular design of navigation bar
inverse, primary , info , default - 4 conceptual color classes available for navigation bar

{%endcomment%}


<nav class="navbar navbar-light "  id="myScrollspy">
<div class="container-fluid">
<div class="navbar-header"> 

<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">

<span class="icon-bar"></span> <!__for those 3 bars__>
<span class="icon-bar"></span>
<span class="icon-bar"></span>

</button>                                                                         
</div>

<div class="collapse navbar-collapse" id="topNavBar">
<ul class= "nav navbar-nav">

<li  class="">
<a href ="{%url 'post_list' %} ">
<font size="5" ><span class="glyphicon glyphicon-home" aria-hidden="true">Home</span></font>&nbsp;

</a>   </li>


<li  class="">
<a href ="{%url 'post_detail' pk=4 %} ">
<font size="5" ><span class="glyphicon glyphicon-hand-o-right" aria-hidden="true">About</span></font>&nbsp;

</a>   </li>


<li >

<span class="glyphicon glyphicon-" aria-hidden="true">

 <div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" 
  style="font-family:serif; font-size: 22px;">
  Categories
  <span class="caret"></span></button>
  <ul class="dropdown-menu">

  {%for category in categories%}
  {%if category.category_type == "Poems"%}
  {%endif%}
  {%endfor%}









<li><a href="{% url 'poem_pg'  %}" style="font-family:fantasy; font-size: 22px;color: brown;">
    Poems</a></li>
<li><a href="{% url 'article_pg'  %}"  style="font-family:fantasy; font-size: 22px;color: brown;">
    Articles</a></li>
<li><a href="{% url 'review_pg'  %}" style="font-family:fantasy; font-size: 22px;color: brown;">
    Reviews</a></li>





{%comment%}
    <li><a href="{% url 'filtered_post_list' name=category.category_type num=3 %}" 
    style="font-family:fantasy; font-size: 22px;color: brown;">
    Poems</a></li>

    <li><a href="{% url 'filtered_post_list' name=category.category_type num=2 %}"  
     style="font-family:fantasy; font-size: 22px;color: brown;">
    Articles</a></li>


    <li><a href="{% url 'filtered_post_list' name=category.category_type num=1 %}"  
     style="font-family:fantasy; font-size: 22px;color: brown;">
    Reviews</a></li>
{%endcomment%}


  </ul>
</div> 

</span>&nbsp;

</li>

</ul>

<form class="navbar-form navbar-left" role="search" method="GET" action=" " >
<div class="form-group">
<input type="text" class="form-control" name="q" placeholder="Articles Poems Reviews" value="{{request.GET.q}}"/>  </div>

<button type="submit" class="btn btn-primary" style="font-family:serif; font-size: 15px;"><span class="glyphicon glyphicon-search" >Search</span></button>
</form>

<ul class="nav navbar-nav navbar-right"   > <!__ nav navbar-nav navbar-right__>





{%if user.is_authenticated%}
<ul class= "nav navbar-nav">
<li  class="nav navbar-nav navbar-left">
<a href = "{% url 'post_new'%}">
<span class="glyphicon glyphicon-plus" aria-hidden="true"><font size="5" >Addpost</font></span>&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</a>
</li>



<li  class="nav navbar-nav navbar-left">
<a href = "{% url 'post_draft_list'%}">
<span class="glyphicon glyphicon-" aria-hidden="true"><font size="5" >Drafts</font></span>&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</a>
</li>


<li  class="nav navbar-nav navbar-right">
<a href = "{% url 'logout_view' %}">
<span class="glyphicon glyphicon-off" aria-hidden="true"><font size="5" >Logout</font></span>&nbsp;
&nbsp;&nbsp;&nbsp;
</a>
</li>

</ul>
{%endif%}
<!--if we use ul class navnavbar nav and then insert urls n li tag , create button when we go to that link.  dont use div, use ul and li tags-->




{%if not user.is_authenticated%}

<ul class= "nav navbar-nav">

<li  class="nav navbar-nav navbar-right">
<a href = "{% url 'register' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<font size="5" ><span class="glyphicon glyphicon-check" aria-hidden="true">Signup</span></font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</a>
</li>


<li class="nav navbar-nav navbar-">
<a href = "{% url 'login_user' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<font size="5" ><span class="glyphicon glyphicon" aria-hidden="true">Login</span></font>

</a>
</li>


</ul>
{%endif%}

</nav>
</div>
</div>

</a>   </li>

{%block part%}  <!__for post_list __>

<div class="content container">
<div class="row">
<div class="col-md-8">
{% block content %}  <!__for post_detail , post_edit __>
{% endblock %}
</div>
</div>
</div>


</body>
</html>

{%endblock%}

<!--
{%block body%}  
{%endblock%}-->

{% block register %}  <!__for registration form__>
{% endblock %}


{% block login %}  <!__for login.html __>
{% endblock %}



{%block content2%}
{%endblock%}

{%block content4%}   <!__for category_list__>
{%endblock%}



{%block poem%}
{%endblock%}

{%block article%}
{%endblock%}

{%block review%}
{%endblock%}

blog/templates/blog/blog_sidebar.html
<h4><a href="{% url 'category_list' %}">Categories</a></h4>

{%comment%}
{% for category in categories %}
<h6><a href="{% url 'filtered_post_list' name=category.category_type num=category.pk %}">{{category.category_type}}</a></h6>
{% endfor %}
{%endcomment%}













            {%comment recent%}
-------------------------------------------------------------------------------------------
<div class="col-sm-3" style="padding-top: 20px;">
	<div class="row">
		<div class="col-sm-12 col-xs-6 text-default text-left side-widget">
			<h4><a href="{% url 'post_list' %}">Recent posts</a></h4>
			{% for recent_post in recent_posts %}
			<h6><a href="{% url 'post_detail' pk=recent_post.pk %}">{{recent_post.title}}</a></h6>
			{% endfor %}
		</div>
		<div class="col-sm-12 col-xs-6 text-default text-left side-widget">
			<h4><a href="{% url 'post_list' %}">Recent Comments</a></h4>
			{% for recent_comment in recent_comments %}
			<h6>
				<a href="{% url 'post_detail' pk=recent_comment.post.pk %}">
				{{recent_comment.author}}
				<span>on</span>
				{{recent_comment.post.title}}
				</a>
			</h6>
			{% endfor %}
		</div>
        {%endcomment%}

blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}
{% block content4 %}


			{% for category in categories %}
								<a href="{% url 'filtered_post_list' name=category.category_type num=category.pk %}" ><h2>{{category.category_type}}</h2></a>
								{% if user.is_superuser %}
								<a class="pull-right" href="{% url 'category_remove' name=category.category_type pk=category.pk %}">
									<button type="button" class="btn btn-custom btn-margin">
										<span class="glyphicon glyphicon-remove" ></span>
								        Delete
								    </button>
								</a>
								{% endif %}

			{% endfor %}


{% endblock %}


 {% include 'blog/blog_sidebar.html' %}

blog/templates/blog/form-template.html
{%for field in form%}

<head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script>
                $(function() {
                        $( "#id_publish" ).datepicker({
                                dateFormat: "yy-mm-dd",
                                defaultDate: "+1w",
                                changeMonth: true,
                                numberOfMonths: 2,
                                onClose: function( selectedDate ) {
                                        $( "#id_service_date" ).datepicker( "option", "minDate", selectedDate );
                                }
                        });
                });
        </script>



</head>











    <div class="form-group">
        <div class="col-sm-offset-2-col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>

        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}&nbsp;</label>


        <div class="col-sm-10">{{field}}</div>
        <!actual inputarea>
    </div>
{%endfor%}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block title %}Log In{% endblock %}


{% block login %}

{%if q%}
<font style="font-family: arial; color: red;"> You have been successfully registered. Please login to continue.</font>
{%endif%}
<div class="container-fluid">

<div class="row">
<div class="col-sm-12 col-md-6">
<div class="panel panel-default">
<div class="panel-body">
<h3>Log In</h3>
{%comment aa%}  {%endcomment%}
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}


<form class="form-horizontal" role="form" action="{% url 'login_user'%}" method="post" enctype="multipart/form-data">

{% csrf_token %}
<div class="form-group">
<label class="control-label col-sm-2" for="id_username">
Username:
</label>
<div class="col-sm-10">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input id="id_username" maxlength="30" name="username" type="text">
</div>
</div>
<div class="form-group">
<label class="control-label col-sm-2" for="id_password">Password:
</label>
<div class="col-sm-10">
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <input id="id_password" maxlength="30" name="password" type="password">
</div>
</div>
<div class="form-group">
<div class="col-sm-offset-2 col-sm-10">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<button type="submit" class="btn btn-danger" align="center">Submit</button>
</div>
</div>
</form>

<div class="panel-footer">
<br>Don't have an account? <a href="{% url 'register' %}">Click here</a> to register.
</div>
</div>
</div>
</div>
</div>

</div>

{% endblock %}

blog/templates/blog/poem_pg.html
{%extends 'blog/base.html' %}

{%block poem%}


{%for post in posts%}
{%if post.category.category_type == "Poems"%}

<div class="postA">
 <h4><a href="{% url 'post_detail' pk=post.pk %}" >{{ post.title }}</a></h4>

{%endif%}
{%endfor%}



{%endblock%}

blog/templates/blog/review_pg.html
{%extends 'blog/base.html' %}

{%block review%}

{%for post in posts%}
{%if post.category.category_type == "Reviews"%}

<div class="postA">
<h4><a href="{% url 'post_detail' pk=post.pk %}" >{{ post.title }}</a></h4>

{%endif%}
{%endfor%}
{%endblock%}